export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_VENDORS = "GET_ALL_VENDORS";
export const GET_VENDOR = "GET_VENDOR";
export const DELETE_VENDOR = "DELETE_VENDOR";
export const CREATE_UPDATE_VENDOR = "CREATE_UPDATE_VENDOR";
export const CREATE_UPDATE_FORECAST = "CREATE_UPDATE_FORECAST";
export const SEARCH_RESULT = "SEARCH_RESULT";
export const GET_ALL_FORECASTS = "GET_ALL_FORECASTS";
export const GET_FORECAST = "GET_FORECAST";
export const GET_FORECAST_SUMMARY = "GET_FORECAST_SUMMARY";
export const DELETE_FORECAST = "DELETE_FORECAST";

export const GET_BOM_DETAILS = "GET_BOM_DETAILS";
export const GET_BOM_LINE_BY_ID = "GET_BOM_LINE_BY_ID";
export const DELETE_BOM_LINE = "DELETE_BOM_LINE";
export const CREATE_UPDATE_BOM = "CREATE_UPDATE_BOM";

export const GET_ALL_SUBTYPES = "GET_ALL_SUBTYPES";
export const GET_SUBTYPE = "GET_SUBTYPE";
export const CREATE_UPDATE_SUBTYPE = "CREATE_UPDATE_SUBTYPE";
export const DELETE_SUBTYPE = "DELETE_SUBTYPE";

export const GET_ALL_MATERIALTYPES = "GET_ALL_MATERIALTYPES";
export const GET_MATERIALTYPE = "GET_MATERIALTYPE";
export const CREATE_UPDATE_MATERIALTYPE = "CREATE_UPDATE_MATERIALTYPE";
export const DELETE_MATERIALTYPE = "DELETE_MATERIALTYPE";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const CREATE_UPDATE_CATEGORY = "CREATE_UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_ALL_DEPARTMENTS="GET_ALL_DEPARTMENTS";